# Generated by Django 4.1.7 on 2023-03-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_agencies_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='for_agency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.agencies'),
            preserve_default=False,
        ),
    ]
