# Generated by Django 4.1.7 on 2023-03-13 17:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_agencies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencies',
            name='blog',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog'),
        ),
    ]
