# Generated by Django 4.1.7 on 2023-03-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_agencies_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencies',
            name='description',
        ),
    ]
