# Generated by Django 4.1.7 on 2023-03-14 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_agencies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='agency',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='base.agencies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
