# Generated by Django 4.1.7 on 2023-03-14 02:39

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_travelpackage_agency_alter_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='contact_name',
            field=models.CharField(default='No Name', max_length=254),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='contact_number',
            field=models.CharField(default='No Number', max_length=254),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='departure_city',
            field=models.CharField(default='No Specified', max_length=254),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='end_city',
            field=models.CharField(default='No Specified', max_length=254),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='start_data',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='type_of_trip',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='destinations',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='destinations',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
