# Generated by Django 4.1.7 on 2023-03-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_travelpackage_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpackage',
            old_name='destinations',
            new_name='destination',
        ),
    ]
