# Generated by Django 4.1.7 on 2023-03-14 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_destinations_travelpackage_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpackage',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
