# Generated by Django 4.1.7 on 2023-03-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_alter_travelpackage_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='AgencyReview',
        ),
        migrations.CreateModel(
            name='PackageReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.travelpackage')),
            ],
        ),
    ]
