# Generated by Django 4.1.7 on 2023-03-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_review_agencyreview_packagereview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agencies',
            new_name='Agencie',
        ),
    ]
