# Generated by Django 4.1.7 on 2023-03-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_reservations_featuredtravelpackage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageReview',
        ),
    ]
