# Generated by Django 4.1.7 on 2023-03-14 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0015_delete_packagereview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agencie',
            new_name='Agencies',
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('company_description', models.TextField()),
                ('website_link', models.URLField()),
                ('registration_number', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
