# Generated by Django 4.1.7 on 2023-03-14 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_agencie_agencies_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='admin_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agency',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agency',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agency',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
