# Generated by Django 4.1.7 on 2023-03-14 10:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_agency_admin_name_alter_agency_agency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='blog',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog'),
        ),
        migrations.AddField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='/uploads/agencies'),
        ),
        migrations.AlterField(
            model_name='agencyreview',
            name='for_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.agency'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.agency'),
        ),
        migrations.DeleteModel(
            name='Agencies',
        ),
    ]
