# Generated by Django 4.1.7 on 2023-03-14 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_agency_blog_agency_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='Agencie',
        ),
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
