# Generated by Django 4.1.7 on 2023-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/agencies/'),
        ),
        migrations.AlterField(
            model_name='agencie',
            name='registration_number',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(upload_to='uploads/travel_package_images/'),
        ),
    ]
