# Generated by Django 5.0.3 on 2024-03-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agencyreview',
            name='for_agency',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencyreview',
            name='author',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='package',
        ),
        migrations.DeleteModel(
            name='Agencie',
        ),
        migrations.DeleteModel(
            name='AgencyReview',
        ),
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
