# Generated by Django 5.0.3 on 2024-03-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_agencie_user_remove_agencyreview_for_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='departure_city',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='end_city',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='type_of_trip',
        ),
        migrations.DeleteModel(
            name='FeaturedPackage',
        ),
    ]
