# Generated by Django 5.0.3 on 2024-03-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_travelpackage_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='base.travelpackage')),
            ],
        ),
    ]
