# Generated by Django 5.0.3 on 2024-03-09 10:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
