# Generated by Django 5.0.3 on 2024-03-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_destination_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='package',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='destinations',
            field=models.ManyToManyField(related_name='destinations', to='base.destination'),
        ),
    ]
